Repository dchbx/gluedb, pull requests merged in 2018-03, with the labels that each got.

#210 22932: Bump Glue Gemfile for Changes from 22821
  Gemfile.lock
Labels: Mergeable: Yes, Priority: Immediate, Status: Functional Testing, Tracker: Data

#182 20807: Plan change for a COBRA enrollment with Dependent add or drops has Glue incorrectly populating end dates on previous policy
  app/models/enrollment_action/action_publish_helper.rb
  app/models/enrollment_action/plan_change.rb
  app/models/enrollment_action/plan_change_dependent_add.rb
  app/models/enrollment_action/plan_change_dependent_drop.rb
  app/models/enrollment_action/termination_date_helper.rb
  spec/models/enrollment_action/change_product_member_add_spec.rb
  spec/models/enrollment_action/plan_change_dependent_drop_spec.rb
  spec/models/enrollment_action/plan_change_spec.rb
  spec/models/enrollment_action/termination_date_helper_spec.rb
Labels: Assignee: NOT ASSIGNED, Priority: High, Status: Resolved, Tracker: App-Dev_Use Case

#211 23049: Update Glue User Audit Query to Include Last Login Time
  script/queries/all_users_by_role.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Security

#213 23212: Dependent cancels showing up on audit files
  app/data_migrations/generate_audits_via_cv2.rb
  spec/data_migrations/generate_audits_via_cv2_spec.rb
  spec/factories/enrollees.rb
  spec/factories/policies.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Promote to Test Environment, Tracker: Bug
