Repository dchbx/gluedb, pull requests merged in 2021-02, with the labels that each got.

#369 92528
  app/models/federal_reports/report_processor.rb
  app/models/observers/policy_updated.rb
  spec/models/observers/policy_updated_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Hot Fix

#372 92575
  app/models/policy.rb
  spec/models/policy_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#360 92226
  app/controllers/payment_processor_uploads_controller.rb
  app/models/payment_processor_upload.rb
  app/models/validators/shop_enrollment_validator.rb
  app/views/layouts/_main_nav.html.haml
  app/views/payment_processor_uploads/_form.html.haml
  app/views/payment_processor_uploads/new.html.haml
  config/routes.rb
  spec/features/payment_processor_upload/uploading_cancel_spec.rb
  spec/features/payment_processor_upload/uploading_individual_cv_spec.rb
  spec/features/payment_processor_upload/uploading_shop_cv_spec.rb
Labels: Assignee: Sheheryar Tariq, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: App-Dev_User Story
